### ISSUE TITLE
Grats !

### ISSUE THREAD

**Issue by perfaram** [scientia-potentia-est/display#1]
Whoo, you should career in ransomware development. Took me a bit more than 1 hour to get rid of it (the worse is that music. Truly — however, just plug a dead earset in the Mac and you're fine)

**Comment by couchfault** [comment]
Wow, someone found our shitty prank program! Honestly it was only intended to prank friends. I was trying to solve the earset problem a while ago but there don't appear to be any apis for changing that. It's part of a data structure that's not writable :(

**Comment by perfaram** [comment]
Glad you couldn't solve it - my MacBook could have learned to fly through my window :laughing:
And that launchd plist - I had to boot on my external HD to get rid of it.

**Comment by couchfault** [comment]
Sorry to hear that, I didn't really expect anyone to download it. Sophomore year in high school gets slow sometimes and I wrote this to mess with some of my classmates. For future reference, I generally remove it from single user mode.

**Comment by perfaram** [comment]
That's no problem! I l knew what I was downloading, I just didn't expect the launchd trick.

**Comment by perfaram** [comment]
Hey, sophomore ? – me too !
